// crypto.go provides cryptographic helpers: ephemeral TLS certificate
// generation, XOR-based signal obfuscation, HMAC-based authentication tokens,
// HTTPS handshake pre-auth handling, and mutual TLS fingerprint verification
// used by the optional TLS code-1 handshake.
package common

import (
	"bytes"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"crypto/tls"
	"crypto/x509"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"math/big"
	"net/http"
	"strings"
	"time"

	"github.com/NodePassProject/nodepass/internal/transport"
)

// NewTLSConfig generates an ephemeral ECDSA P-256 self-signed certificate in RAM and returns a tls.Config.
// The certificate is valid for one year, never stored on disk, and automatically discarded on shutdown.
// Provides forward secrecy: each tunnel instance gets a unique certificate, preventing replay across restarts.
// Used by both server and client sides to establish encrypted TLS connections with certificate-based validation.
func NewTLSConfig() (*tls.Config, error) {
	private, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, err
	}

	serialNumber, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return nil, err
	}

	template := x509.Certificate{
		SerialNumber: serialNumber,
		NotBefore:    time.Now(),
		NotAfter:     time.Now().AddDate(1, 0, 0),
		KeyUsage:     x509.KeyUsageKeyEncipherment | x509.KeyUsageDigitalSignature,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	}

	crtBytes, err := x509.CreateCertificate(rand.Reader, &template, &template, &private.PublicKey, private)
	if err != nil {
		return nil, err
	}

	keyBytes, err := x509.MarshalPKCS8PrivateKey(private)
	if err != nil {
		return nil, err
	}

	crtPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: crtBytes})
	keyPEM := pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: keyBytes})

	cert, err := tls.X509KeyPair(crtPEM, keyPEM)
	if err != nil {
		return nil, err
	}

	return &tls.Config{Certificates: []tls.Certificate{cert}}, nil
}

// FormatCertFingerprint returns the SHA-256 fingerprint of a DER-encoded certificate as a hex string.
// Used in TLS code-1 feature to identify and compare certificates for mutual verification.
func (c *Common) FormatCertFingerprint(certRaw []byte) string {
	hash := sha256.Sum256(certRaw)
	return hex.EncodeToString(hash[:])
}

// Xor XOR-obfuscates data in-place using TunnelKey as a repeating cipher key and returns the same slice.
// Intentionally lightweight and not cryptographically strong; provides wire-format obfuscation only.
// Called by Encode during signal transmission and by Decode during signal reception.
func (c *Common) Xor(data []byte) []byte {
	for i := range data {
		data[i] ^= c.TunnelKey[i%len(c.TunnelKey)]
	}
	return data
}

// GenerateAuthToken produces an HMAC-SHA256 authentication token derived from TunnelKey.
// Used for pre-authentication with HTTP CONNECT proxies that require credentials.
// Returns the hex-encoded HMAC value.
func (c *Common) GenerateAuthToken() string {
	return hex.EncodeToString(hmac.New(sha256.New, []byte(c.TunnelKey)).Sum(nil))
}

// VerifyAuthToken performs constant-time comparison of the provided token against
// the expected HMAC generated by GenerateAuthToken. Safe against timing attacks.
func (c *Common) VerifyAuthToken(token string) bool {
	return hmac.Equal([]byte(token), []byte(c.GenerateAuthToken()))
}

// VerifyPreAuth checks whether an HTTP request carries valid Basic Proxy-Authorization credentials
// where the username matches TunnelKey. Returns true if credentials are valid and authenticated.
// Used to validate pre-authentication headers on HTTP CONNECT proxy requests.
func (c *Common) VerifyPreAuth(r *http.Request) bool {
	decoded, err := base64.StdEncoding.DecodeString(strings.TrimPrefix(r.Header.Get("Proxy-Authorization"), "Basic "))
	return err == nil && strings.HasPrefix(string(decoded), c.TunnelKey+":")
}

// HandlePreAuth hijacks an HTTPS CONNECT request that has passed VerifyPreAuth, dials the target,
// sends "200 Connection established" to the client, and bidirectionally forwards data between them.
// Used when the tunnel is accessed through a sampling request that requires pre-authentication.
func (c *Common) HandlePreAuth(w http.ResponseWriter, r *http.Request) {
	hj, ok := w.(http.Hijacker)
	if !ok {
		return
	}
	clientConn, _, err := hj.Hijack()
	if err != nil {
		return
	}
	defer clientConn.Close()

	dialFunc := c.GetDialFunc("tcp", TCPDialTimeout)
	targetConn, err := dialFunc(r.URL.Host)
	if err != nil {
		return
	}
	defer targetConn.Close()

	clientConn.Write([]byte("HTTP/1.1 200 Connection established\r\n\r\n"))

	buffer1 := c.GetTCPBuffer()
	buffer2 := c.GetTCPBuffer()
	defer func() {
		c.PutTCPBuffer(buffer1)
		c.PutTCPBuffer(buffer2)
	}()

	transport.DataExchange(clientConn, targetConn, c.ReadTimeout, buffer1, buffer2)
}

// Encode XOR-obfuscates data with TunnelKey, base64-encodes the result, appends a newline,
// and returns the wire-ready signal frame (encoded as bytes). Reverses with Decode.
func (c *Common) Encode(data []byte) []byte {
	return append([]byte(base64.StdEncoding.EncodeToString(c.Xor(data))), '\n')
}

// Decode reverses Encode: strips the trailing newline, base64-decodes the string, then
// XOR-deobfuscates with TunnelKey and returns the original plaintext signal bytes.
// Returns an error if base64 decoding fails.
func (c *Common) Decode(data []byte) ([]byte, error) {
	decoded, err := base64.StdEncoding.DecodeString(string(bytes.TrimSuffix(data, []byte{'\n'})))
	if err != nil {
		return nil, fmt.Errorf("Decode: base64 decode failed: %w", err)
	}
	return c.Xor(decoded), nil
}

// IncomingVerify initiates TLS code-1 certificate fingerprint verification (client-side in pooled mode).
// Waits for the pool to be ready, retrieves a test connection, extracts the certificate fingerprint,
// and sends a "verify" signal to the remote side for comparison. Cancels the tunnel on errors.
// Called as a background goroutine during HealthCheck when TLSCode == "1".
func (c *Common) IncomingVerify() {
	for c.Ctx.Err() == nil {
		if c.TunnelPool.Ready() && c.TunnelPool.Active() > 0 {
			break
		}
		select {
		case <-c.Ctx.Done():
			continue
		case <-time.After(ContextCheckInterval):
		}
	}

	id, testConn, err := c.TunnelPool.IncomingGet(PoolGetTimeout)
	if err != nil {
		c.Logger.Error("IncomingVerify: incomingGet failed: %v", err)
		c.Cancel()
		return
	}
	defer testConn.Close()

	var fingerprint string
	switch c.CoreType {
	case "server":
		if c.TLSConfig != nil && len(c.TLSConfig.Certificates) > 0 {
			cert := c.TLSConfig.Certificates[0]
			if len(cert.Certificate) > 0 {
				fingerprint = c.FormatCertFingerprint(cert.Certificate[0])
			}
		}
	case "client":
		if conn, ok := testConn.(interface{ ConnectionState() tls.ConnectionState }); ok {
			state := conn.ConnectionState()
			if len(state.PeerCertificates) > 0 {
				fingerprint = c.FormatCertFingerprint(state.PeerCertificates[0].Raw)
			}
		}
	}

	if c.Ctx.Err() == nil && c.ControlConn != nil {
		signalData, _ := json.Marshal(Signal{
			ActionType:  "verify",
			PoolConnID:  id,
			Fingerprint: fingerprint,
		})
		c.WriteChan <- c.Encode(signalData)
	}

	c.Logger.Debug("TLS code-1: verify signal: cid %v -> %v", id, c.ControlConn.RemoteAddr())
}

// OutgoingVerify handles incoming "verify" signals from TLS code-1 verification (server-side in pooled mode).
// Waits for the pool to be ready, retrieves the designated pool connection, extracts its certificate fingerprint,
// and compares it against the fingerprint received in the signal. On mismatch, cancels the context (aborting the tunnel).
// On match, signals VerifyChan to unblock TunnelLoop. Called as a background goroutine from TunnelOnce.
func (c *Common) OutgoingVerify(signal Signal) {
	for c.Ctx.Err() == nil {
		if c.TunnelPool.Ready() {
			break
		}
		select {
		case <-c.Ctx.Done():
			continue
		case <-time.After(ContextCheckInterval):
		}
	}

	fingerPrint := signal.Fingerprint
	if fingerPrint == "" {
		c.Logger.Error("OutgoingVerify: no fingerprint in signal")
		c.Cancel()
		return
	}

	id := signal.PoolConnID
	c.Logger.Debug("TLS verify signal: cid %v <- %v", id, c.ControlConn.RemoteAddr())

	testConn, err := c.TunnelPool.OutgoingGet(id, PoolGetTimeout)
	if err != nil {
		c.Logger.Error("OutgoingVerify: request timeout: %v", err)
		c.Cancel()
		return
	}
	defer testConn.Close()

	var serverFingerprint, clientFingerprint string
	switch c.CoreType {
	case "server":
		if c.TLSConfig == nil || len(c.TLSConfig.Certificates) == 0 {
			c.Logger.Error("OutgoingVerify: no local certificate")
			c.Cancel()
			return
		}

		cert := c.TLSConfig.Certificates[0]
		if len(cert.Certificate) == 0 {
			c.Logger.Error("OutgoingVerify: empty local certificate")
			c.Cancel()
			return
		}

		serverFingerprint = c.FormatCertFingerprint(cert.Certificate[0])
		clientFingerprint = fingerPrint
	case "client":
		conn, ok := testConn.(interface{ ConnectionState() tls.ConnectionState })
		if !ok {
			return
		}
		state := conn.ConnectionState()

		if len(state.PeerCertificates) == 0 {
			c.Logger.Error("OutgoingVerify: no peer certificates found")
			c.Cancel()
			return
		}

		clientFingerprint = c.FormatCertFingerprint(state.PeerCertificates[0].Raw)
		serverFingerprint = fingerPrint
	}

	if serverFingerprint != clientFingerprint {
		c.Logger.Error("OutgoingVerify: certificate fingerprint mismatch: server: %v - client: %v", serverFingerprint, clientFingerprint)
		c.Cancel()
		return
	}

	c.Logger.Info("TLS code-1: RAM cert verified with sha256 fingerprint: %v", fingerPrint)

	c.VerifyChan <- struct{}{}
}
